@extends('layouts.icare_app')
@section('navber')
  @include('s_d_navside.nav')
@endsection
@section('sidenav')
  @include('s_d_navside.side')
@endsection
@section('content')
  @include('s_s_page.pro_detail')
@endsection
@section('foot')
  @include('s_d_navside.footer')
@endsection
